-- MySQL Script generated by MySQL Workbench
-- mar 10 oct 2017 07:47:55 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema doctorado_2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `doctorado_2` ;

-- -----------------------------------------------------
-- Schema doctorado_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doctorado_2` DEFAULT CHARACTER SET utf8 ;
USE `doctorado_2` ;

-- -----------------------------------------------------
-- Table `doctorado_2`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`tipo_documento` (
  `identificador` INT(11) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `correquisitos` INT(11) NULL,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  PRIMARY KEY (`identificador`),
  INDEX `fk_tipo_publicacion_tipo_publicacion1_idx` (`correquisitos` ASC),
  CONSTRAINT `fk_tipo_publicacion_tipo_publicacion1`
    FOREIGN KEY (`correquisitos`)
    REFERENCES `doctorado_2`.`tipo_documento` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doctorado_2`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`usuario` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`usuario` (
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(70) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'activo',
  `usu_id` INT(11) NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`estudiante` (
  `est_cedula` INT(11) NOT NULL,
  `est_codigo` VARCHAR(20) NOT NULL,
  `est_cohorte` INT(4) NOT NULL,
  `est_tutor` VARCHAR(45) NOT NULL,
  `est_semestre` INT(2) NOT NULL,
  `est_creditos` INT(11) NOT NULL,
  `est_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_id` INT(11) NOT NULL,
  UNIQUE INDEX `est_codigo_UNIQUE` (`est_codigo` ASC),
  INDEX `fk_estudiante_usuario1_idx` (`usu_id` ASC),
  UNIQUE INDEX `usu_id_UNIQUE` (`usu_id` ASC),
  UNIQUE INDEX `est_cedula_UNIQUE` (`est_cedula` ASC),
  UNIQUE INDEX `est_id_UNIQUE` (`est_id` ASC),
  PRIMARY KEY (`est_id`),
  CONSTRAINT `fk_estudiante_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `doctorado_2`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`documentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`documentacion` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`documentacion` (
  `doc_identificador` INT(11) NOT NULL AUTO_INCREMENT,
  `doc_hash` VARCHAR(40) NULL DEFAULT NULL,
  `doc_diropkm` VARCHAR(30) NULL DEFAULT NULL,
  `doc_creditos` INT(11) NULL DEFAULT NULL,
  `doc_fecha_visado` DATE NULL DEFAULT NULL,
  `doc_fecha_registro` DATE NULL DEFAULT NULL,
  `doc_estado` VARCHAR(15) NULL DEFAULT NULL,
  `doc_fecha_publicacion` DATE NOT NULL,
  `doc_num_acta` INT(20) NULL DEFAULT NULL,
  `doc_visado` VARCHAR(20) NULL DEFAULT NULL,
  `id_tipo_documentacion` INT(11) NOT NULL,
  `doc_autores_secundarios` VARCHAR(300) NULL,
  `est_id` INT(11) NOT NULL,
  PRIMARY KEY (`doc_identificador`),
  INDEX `fk_publicacion_tipo_publicacion1_idx` (`id_tipo_documentacion` ASC),
  INDEX `fk_documentacion_estudiante1_idx` (`est_id` ASC),
  CONSTRAINT `fk_publicacion_tipo_publicacion1`
    FOREIGN KEY (`id_tipo_documentacion`)
    REFERENCES `doctorado_2`.`tipo_documento` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentacion_estudiante1`
    FOREIGN KEY (`est_id`)
    REFERENCES `doctorado_2`.`estudiante` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`archivo` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`archivo` (
  `arc_tipoPDF_cargar` VARCHAR(40) NOT NULL,
  `doc_identificador` INT(11) NOT NULL,
  PRIMARY KEY (`arc_tipoPDF_cargar`, `doc_identificador`),
  INDEX `fk_archivo_documentacion1_idx` (`doc_identificador` ASC),
  CONSTRAINT `fk_archivo_documentacion1`
    FOREIGN KEY (`doc_identificador`)
    REFERENCES `doctorado_2`.`documentacion` (`doc_identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`capitulo_libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`capitulo_libro` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`capitulo_libro` (
  `doc_identificador` INT(11) NOT NULL,
  `caplib_titulo_libro` VARCHAR(200) NOT NULL,
  `caplib_titulo_capitulo` VARCHAR(80) NOT NULL,
  `caplib_isbn` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`doc_identificador`),
  INDEX `fk_capitulo_libro_publicacion1_idx` (`doc_identificador` ASC),
  UNIQUE INDEX `caplib_isbn_UNIQUE` (`caplib_isbn` ASC),
  CONSTRAINT `fk_capitulo_libro_publicacion1`
    FOREIGN KEY (`doc_identificador`)
    REFERENCES `doctorado_2`.`documentacion` (`doc_identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`congreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`congreso` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`congreso` (
  `doc_identificador` INT(11) NOT NULL,
  `cong_titulo_ponencia` VARCHAR(200) NOT NULL,
  `cong_nombre_evento` VARCHAR(100) NOT NULL,
  `cong_tipo_congreso` VARCHAR(30) NOT NULL,
  `cong_doi` VARCHAR(30) NOT NULL,
  `cong_issn` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`doc_identificador`),
  INDEX `fk_congreso_publicacion1_idx` (`doc_identificador` ASC),
  CONSTRAINT `fk_congreso_publicacion1`
    FOREIGN KEY (`doc_identificador`)
    REFERENCES `doctorado_2`.`documentacion` (`doc_identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`postgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`postgrado` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`postgrado` (
  `id_posgrado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_postgrado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_posgrado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`coordinador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`coordinador` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`coordinador` (
  `id_posgrado` INT(11) NOT NULL,
  `usu_id` INT(11) NOT NULL,
  INDEX `fk_coordinador_postgrado1_idx` (`id_posgrado` ASC),
  PRIMARY KEY (`id_posgrado`),
  INDEX `fk_coordinador_usuario1_idx` (`usu_id` ASC),
  CONSTRAINT `fk_coordinador_postgrado1`
    FOREIGN KEY (`id_posgrado`)
    REFERENCES `doctorado_2`.`postgrado` (`id_posgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordinador_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `doctorado_2`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`tipo_usuario` (
  `descripcion` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`grupo_tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`grupo_tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`grupo_tipo_usuario` (
  `tipo` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(45) BINARY NOT NULL,
  `usu_id` INT(11) NOT NULL,
  INDEX `fk_grupo_tipo_usuario_tipo_usuario1_idx` (`tipo` ASC),
  INDEX `fk_grupo_tipo_usuario_usuario1_idx` (`usu_id` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  PRIMARY KEY (`usu_id`),
  CONSTRAINT `fk_grupo_tipo_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo`)
    REFERENCES `doctorado_2`.`tipo_usuario` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_tipo_usuario_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `doctorado_2`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`libro` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`libro` (
  `doc_identificador` INT(11) NOT NULL,
  `lib_titulo_libro` VARCHAR(200) NOT NULL,
  `lib_isbn` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`doc_identificador`),
  INDEX `fk_libro_publicacion1_idx` (`doc_identificador` ASC),
  UNIQUE INDEX `lib_isbn_UNIQUE` (`lib_isbn` ASC),
  CONSTRAINT `fk_libro_publicacion1`
    FOREIGN KEY (`doc_identificador`)
    REFERENCES `doctorado_2`.`documentacion` (`doc_identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`revista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`revista` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`revista` (
  `doc_identificador` INT(11) NOT NULL,
  `rev_nombre_revista` VARCHAR(80) NOT NULL,
  `rev_titulo_articulo` VARCHAR(200) NOT NULL,
  `rev_categoria` VARCHAR(2) NOT NULL,
  `rev_doi` VARCHAR(30) NULL,
  PRIMARY KEY (`doc_identificador`),
  INDEX `fk_revista_publicacion1_idx` (`doc_identificador` ASC),
  CONSTRAINT `fk_revista_publicacion1`
    FOREIGN KEY (`doc_identificador`)
    REFERENCES `doctorado_2`.`documentacion` (`doc_identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `doctorado_2`.`estudiante_posgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`estudiante_posgrado` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`estudiante_posgrado` (
  `id_posgrado` INT(11) NOT NULL,
  `est_id` INT(11) NOT NULL,
  INDEX `fk_estudiante_posgrado_postgrado1_idx` (`id_posgrado` ASC),
  PRIMARY KEY (`id_posgrado`, `est_id`),
  INDEX `fk_estudiante_posgrado_estudiante1_idx` (`est_id` ASC),
  CONSTRAINT `fk_estudiante_posgrado_postgrado1`
    FOREIGN KEY (`id_posgrado`)
    REFERENCES `doctorado_2`.`postgrado` (`id_posgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_posgrado_estudiante1`
    FOREIGN KEY (`est_id`)
    REFERENCES `doctorado_2`.`estudiante` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doctorado_2`.`pasantia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctorado_2`.`pasantia` ;

CREATE TABLE IF NOT EXISTS `doctorado_2`.`pasantia` (
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_terminacion` VARCHAR(45) NULL,
  `lugar` VARCHAR(45) NULL,
  `documentacion_doc_identificador` INT(11) NOT NULL,
  PRIMARY KEY (`documentacion_doc_identificador`),
  CONSTRAINT `fk_pasantia_documentacion1`
    FOREIGN KEY (`documentacion_doc_identificador`)
    REFERENCES `doctorado_2`.`documentacion` (`doc_identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
